apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachineDisk
metadata:
  name: windows7-boot
  namespace: vms
spec:
  size: 25Gi
  storageClassName: robin-vm-repl-2-block-immediate
  # Google Cloud Storage import reference
  source:
    gcs:
      url: gs://living-on-the-edge-vm-images/windows7.qcow2
      secretRef: vm-image-importer
