apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachineBackupPlan
metadata:
  name: vm-hourly-backup-schedule-to-minio
  namespace: vms
spec:
  backupConfig:
    backupRepository: minio-backup-repo
    backupScope:
      selectedVirtualMachines:
      # - resourceName: haiku
      - resourceName: kdeneon
      - resourceName: windows10
      # - resourceName: windows11
    volumeStrategy: Portable
  backupSchedule:
    cronSchedule: 05 * * * *  # Every hour
    paused: false
  retentionPolicy:
    backupDeleteLockDays: 15
    backupRetainDays: 30
    locked: false
