# Copyright 2024 Google. This software is provided as-is, without warranty or
# representation for any use or purpose. Your use of it is subject to your agreement
# with Google.

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Values.name }}-{{ .Values.rbac.clusterRoleBindingSuffix }}"
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: "{{ .Values.name }}-{{ .Values.rbac.clusterRoleNameSuffix }}"
  apiGroup: rbac.authorization.k8s.io
