apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachine
metadata:
  name: kdeneon
  namespace: vms
spec:
  osType: Linux
  compute:
    cpu:
      vcpus: 8
    memory:
      capacity: 16Gi
  disks:
  - boot: true
    driver: virtio
    virtualMachineDiskName: kdeneon
  interfaces:
  - default: true
    name: eth0
    networkName: pod-network

---

apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachineDisk
metadata:
  name: kdeneon
  namespace: vms
spec:
  size: 20Gi
  storageClassName: robin-vm-repl-2-block-immediate
  source:
    gcs:
      url: gs://living-on-the-edge-vm-images/KDENeon.qcow2
      secretRef: vm-image-importer

---
apiVersion: v1
kind: Service
metadata:
  name: remote-access-to-kdeneon
  namespace: vms
spec:
  # type: LoadBalancer
  ports:
  - name: rdp-tcp
    port: 3389
    protocol: TCP
    targetPort: 3389
  - name: rdp-udp
    port: 3389
    protocol: UDP
    targetPort: 3389
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  - name: vnc
    port: 5900
    protocol: TCP
    targetPort: 5900
  selector:
    kubevirt/vm: kdeneon
