# Notes
# 1. copy installer isos to GCS bucket
# 2. Create an empty VM Disk
#
apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachine
metadata:
  name: windows10
  namespace: vms
spec:
  osType: Windows
  disks:
    - boot: true
      virtualMachineDiskName: windows10-boot
      driver: virtio
    # - virtualMachineDiskName: windows-iso
    # - virtualMachineDiskName: virtio-driver
  compute:
    cpu:
      vcpus: 4
    memory:
      capacity: 8Gi
  interfaces:
    - name: eth0
      networkName: pod-network
      default: true

---
# apiVersion: vm.cluster.gke.io/v1
# kind: VirtualMachineDisk
# metadata:
#   name: windows10-boot
#   namespace: vms
# spec:
#   size: 30Gi
#   storageClassName: robin-vm-repl-2-block-immediate

---
# apiVersion: vm.cluster.gke.io/v1
# kind: VirtualMachineDisk
# metadata:
#   name: windows10-boot
#   namespace: vms
# spec:
#   size: 20Gi
#   storageClassName: robin-vm-repl-2-block-immediate
#   source:
#     gcs:
#       url: gs://living-on-the-edge-vm-images/Windows-10.qcow2
#       secretRef: vm-image-importer





apiVersion: v1
kind: Service
metadata:
  name: remote-access-to-windows10
  namespace: vms
spec:
  type: LoadBalancer
  ports:
  - name: rdp-tcp
    port: 3389
    protocol: TCP
    targetPort: 3389
  - name: rdp-udp
    port: 3389
    protocol: UDP
    targetPort: 3389
  selector:
    kubevirt/vm: windows10

---
apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachineDisk
metadata:
  name: virtio-driver
  namespace: vms
spec:
  size: 1Gi
  source:
    registry:
      url: docker://quay.io/kubevirt/virtio-container-disk:latest
  storageClassName: robin-vm-repl-2-block-immediate
  diskType: cdrom

# ---
# apiVersion: vm.cluster.gke.io/v1
# kind: VirtualMachineDisk
# metadata:
#   name: windows-iso
#   namespace: vms
# spec:
#   source:
#     gcs:
#       url: gs://living-on-the-edge-vm-images/Win10_22H2_English_x64v1.iso
#       secretRef: vm-image-importer
#   size: 10Gi
#   storageClassName: robin-vm-repl-2-block-immediate
#   diskType: cdrom
