# https://kevinlocke.name/bits/2021/12/10/windows-11-guest-virtio-libvirt/
# https://pve.proxmox.com/wiki/Windows_VirtIO_Drivers
# https://www.tomshardware.com/how-to/install-windows-11-without-microsoft-account

apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: windowsxp
  namespace: vms
spec:
  domain:
    firmware:
      bootloader:
        bios: {}
    cpu:
      cores: 1
      model: host-model
      sockets: 1
      threads: 1
    # machine:
    #   type: pc-q35
    devices:
      useVirtioTransitional: true
      disks:
      - name: disk0
        bootOrder: 1
        disk:
          bus: virtio
        serial: windowsxp-boot
      - name: disk1
        bootOrder: 2
        cdrom:
          # bus: virtio
          readonly: true
          tray: closed
        serial: windowsxp-iso
        - name: disk2
          bootOrder: 3
          cdrom:
            bus: sata
            readonly: true
            tray: closed
          serial: virtio-driver
      interfaces:
      - macAddress: f8:8f:ca:00:00:01
        masquerade: {}
        name: eth0
    features:
      acpi:
        enabled: false
    resources:
      requests:
        memory: 2G
  evictionStrategy: LiveMigrate
  networks:
  - name: eth0
    pod: {}
  volumes:
  - dataVolume:
      name: windowsxp-boot
    name: disk0
  - dataVolume:
      name: windowsxp-iso
    name: disk1
  - dataVolume:
      name: fedora-virtio-driver
    name: disk2

---
apiVersion: v1
kind: Service
metadata:
  name: remote-access-to-windowsxp
  namespace: vms
spec:
  type: ClusterIP
  ports:
  - name: rdp-tcp
    port: 3389
    protocol: TCP
    targetPort: 3389
  - name: rdp-udp
    port: 3389
    protocol: UDP
    targetPort: 3389
  selector:
    vm.kubevirt.io/name: windowsxp

# ---
# apiVersion: vm.cluster.gke.io/v1
# kind: VirtualMachineDisk
# metadata:
#   name: windowsxp-boot
#   namespace: vms
# spec:
#   size: 32Gi
#   storageClassName: robin-vm-repl-2-block-immediate


# ---
# apiVersion: vm.cluster.gke.io/v1
# kind: VirtualMachineDisk
# metadata:
#   name: fedora-virtio-driver
#   namespace: vms
# spec:
#   size: 1Gi
#   source:
#     gcs:
#       url: gs://living-on-the-edge-vm-images/isos/virtio-win-0.1.262.iso
#       secretRef: vm-image-importer
#   storageClassName: robin-vm-repl-2-block-immediate
#   diskType: cdrom

# ---
# apiVersion: vm.cluster.gke.io/v1
# kind: VirtualMachineDisk
# metadata:
#   name: windowsxp-iso
#   namespace: vms
# spec:
#   source:
#     gcs:
#       url: gs://living-on-the-edge-vm-images/isos/Win11_23H2_English_x64v2.iso
#       secretRef: vm-image-importer
#   size: 10Gi
#   storageClassName: robin-vm-repl-2-block-immediate
#   diskType: cdrom
