# https://kevinlocke.name/bits/2021/12/10/windows-11-guest-virtio-libvirt/
# https://pve.proxmox.com/wiki/Windows_VirtIO_Drivers
# https://www.tomshardware.com/how-to/install-windows-11-without-microsoft-account

apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: windows11
  namespace: vms
spec:
  domain:
    firmware:
      bootloader:
        efi:
          secureBoot: true
    cpu:
      cores: 4
      model: host-model
      sockets: 1
      threads: 1
    machine:
      type: q35
    devices:
      tpm: {}
      disks:
      - name: disk0
        bootOrder: 1
        disk:
          bus: virtio
        serial: windows11-boot
      # - name: disk1
      #   bootOrder: 2
      #   cdrom:
      #     bus: sata
      #     readonly: true
      #     tray: closed
      #   serial: windows11-iso
      # - name: disk2
      #   bootOrder: 3
      #   cdrom:
      #     bus: sata
      #     readonly: true
      #     tray: closed
      #   serial: virtio-driver
      interfaces:
      - macAddress: f8:8f:ca:00:00:01
        masquerade: {}
        name: eth0
    features:
      acpi:
        enabled: true
      smm:
        enabled: true
    resources:
      requests:
        memory: 8G
  evictionStrategy: LiveMigrate
  networks:
  - name: eth0
    pod: {}
  volumes:
  - dataVolume:
      name: windows11-boot
    name: disk0
  - dataVolume:
      name: windows11-iso
    name: disk1
  - dataVolume:
      name: fedora-virtio-driver
    name: disk2

---
apiVersion: v1
kind: Service
metadata:
  name: remote-access-to-windows11
  namespace: vms
spec:
  type: ClusterIP
  ports:
  - name: rdp-tcp
    port: 3389
    protocol: TCP
    targetPort: 3389
  - name: rdp-udp
    port: 3389
    protocol: UDP
    targetPort: 3389
  selector:
    vm.kubevirt.io/name: windows11
