# Copyright 2024 Google. This software is provided as-is, without warranty or representation
# or any use or purpose. Your use of it is subject to your agreement with Google.

# https://cloud.google.com/distributed-cloud/edge/latest/docs/virtual-machines#enable-anthos-vm-runtime-support
apiVersion: vm.cluster.gke.io/v1
kind: VMRuntime
metadata:
  name: vmruntime
spec:
  # Enable Anthos VM Runtime support
  enabled: true
  # vmImageFormat defaults to "raw" if not set
  vmImageFormat: "raw"
  # Set node grace period to 55 seconds; required for upgrading to 1.7.0
  haPolicy:
    defaultRecoveryStrategy: Reschedule
    nodeHeartbeatInterval: 15s
    nodeMonitorGracePeriod: 55s
