apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachineDisk
metadata:
  name: kdeneon
  namespace: vms
spec:
  size: 25Gi
  storageClassName: robin-vm-repl-2-block-immediate
  source:
    gcs:
      url: gs://living-on-the-edge-vm-images/KDENeon.qcow2
      secretRef: vm-image-importer
