# Copyright 2024 Google. This software is provided as-is, without warranty or
# representation for any use or purpose. Your use of it is subject to your agreement
# with Google.

apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJrcm9nZXJ0ZWNobm9sb2d5LWRvY2tlci1kZXYuamZyb2cuaW8iOnsidXNlcm5hbWUiOiJzOTk4NWpmcm9nUEBrcm9nZXIuY29tIiwicGFzc3dvcmQiOiJjbVZtZEd0dU9qQXhPakUzTXpJNE5qUXlPRFU2WTA1cE5GcEpOa3h0U1hOUk1IRmFRbkUwTldkeVQzTXlabFpMIiwiYXV0aCI6ImN6azVPRFZxWm5KdloxQkFhM0p2WjJWeUxtTnZiVHBqYlZadFpFZDBkVTlxUVhoUGFrVXpUWHBKTkU1cVVYbFBSRlUyV1RBMWNFNUdjRXBPYTNoMFUxaE9VazFJUm1GUmJrVXdUbGRrZVZRelRYbGFiRnBNIn19fQ==
kind: Secret
metadata:
  creationTimestamp: "2024-05-06T16:26:02Z"
  name: jfrog-dev-secret
  namespace: gdce-jumphost
  resourceVersion: "903"
  uid: 14e08645-7e64-4f94-9e8e-8e2472354d9c
type: kubernetes.io/dockerconfigjson
