# Copyright 2024 Google. This software is provided as-is, without warranty or
# representation for any use or purpose. Your use of it is subject to your agreement
# with Google.


# General, global values
name: &appname gdce-jumphost
namespace: gdce-jumphost
serviceAccountName: *appname
containerTimezone: America/New_York
# If jumphostUsername is changed, update the username in the Dockerfile and rebuild
jumphostUsername: jump


# Container Image
image:
  repository: us-central1-docker.pkg.dev/living-on-the-edge/gdce-repo/gdce-jumphost/
  name: *appname
  tag: experimental
  pullPolicy: Always
  pullSecret: jfrog-dev-secret


# Labels
deploymentLabels:
  app: *appname

selectorMatchLabels:
  app: *appname

podLabels:
 app: *appname


# Annotations
podAnnotations:
  networking.gke.io/default-interface: eth1
  networking.gke.io/interfaces: |
    [
      {"interfaceName":"eth0","network":"pod-network"},
      {"interfaceName":"eth1","interface":"gdce-jumphost-networkinterface"}
    ]


# Cluster RBAC
rbac:
  # *appName- will be prepended to these keys in a template.
  clusterRoleNameSuffix: cluster-viewer
  clusterRoleBindingSuffix: clusterrolebinding


# GDCE NetworkInterfaces
networkInterfaceSpec:
  networkName: store-vlan-2100
  ipAddresses: [10.159.172.101/24]
  macAddress: 60:e3:cb:1b:9e:9e
