apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachine
metadata:
  name: ben-test-server
  namespace: default
spec:
  osType: Linux
  compute:
    cpu:
      vcpus: 4
    memory:
      capacity: 8Gi
  interfaces:
    - name: eth0
      networkName: pod-network
      default: false
    - name: eth1
      networkName: store-vlan-2100
      ipAddresses:
        - 10.159.172.102/24
      default: true
  disks:
    - boot: true
      virtualMachineDiskName: ben-test-server-disk

# ---

# apiVersion: vm.cluster.gke.io/v1
# kind: VirtualMachineDisk
# metadata:
#   name: ben-test-server-disk
#   namespace: default
# spec:
#   size: 10Gi
#   storageClassName: robin-vm-repl-2-block-immediate
#   source:
#     gcs:
#       url: gs://appsrv-image/ben-test-server.qcow2
#       secretRef: vm-image-importer
