# https://cloud.google.com/anthos/clusters/docs/bare-metal/latest/how-to/cluster-dns
apiVersion: networking.gke.io/v1alpha1
kind: ClusterDNS
metadata:
  name: default
  annotations:
    configmanagement.gke.io/managed: disabled  # Temporary (thisisben@)
spec:
  upstreamNameservers:
    - serverIP: 8.8.8.8
    - serverIP: 8.8.4.4
    - serverIP: 2001:4860:4860::8888
  domains:
    - name: home
      nameservers:
        - serverIP: 10.0.0.100
  # No special treatment for Google domains, uses default upstream nameservers
  googleAccess: default
