apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  labels:
    app: debug-pod
spec:
  containers:
  - image: ubuntu
    command: ["sleep", "infinity"]
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always
