apiVersion: apps/v1
kind: Deployment
metadata:
  name: metallb-test
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        networking.gke.io/default-interface: eth0
        networking.gke.io/interfaces: |
          [
            {"interfaceName":"eth0","network":"pod-network"},
            {"interfaceName":"eth1","network":"store-vlan-2100"}
          ]
    spec:
      containers:
      # - name: metallb-test
      #   image: nicolaka/netshoot
      #   command: ["/bin/bash"]
      #   args: ["-c", "nc -l -p 8080 -c 'echo -e "HTTP/1.1 200 OK\n\n Hello from $(hostname)"'"]
      #   ports:
      #   - name: http
      #     containerPort: 8080
      - name: metallb-test
        image: nginx:1
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: metallb-test
  namespace: default

spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx
    networking.gke.io/network: store-vlan-2100
  type: LoadBalancer
  loadBalancer:
  metalLB:
    addressPools:
    - name: "my-address-pool-2"
      addresses:
      - "192.0.2.73-192.0.2.80"
      manualAssign: true
  # externalTrafficPolicy: Cluster
  # internalTrafficPolicy: Cluster
