apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: multipleinterface
  annotations:
    networking.gke.io/default-interface: eth0
    networking.gke.io/interfaces: |
          [
            {"interfaceName":"eth0","network":"pod-network"},
            {"interfaceName":"eth1","network":"store-vlan-2100"}
          ]
spec:
  containers:
  - name: network-tester
    image: nicolaka/netshoot
    command: ["sleep", "infinity"]
