# Copyright 2024 Google. This software is provided as-is, without warranty or
# representation for any use or purpose. Your use of it is subject to your agreement
# with Google.

# General, global values
name: &appname gdce-jumphost
namespace: gdce-jumphost
serviceAccountName: *appname
containerTimezone: America/New_York
# If jumphostUsername is changed, update the username in the Dockerfile and rebuild
jumphostUsername: jump

# Container Image
image:
  repository: us-central1-docker.pkg.dev/living-on-the-edge/gdce-repo/
  name: *appname
  tag: '20250403'
  pullPolicy: Always
  pullSecret: artifact-registry

# Labels
deploymentLabels:
  app: *appname

selectorMatchLabels:
  app: *appname

podLabels:
  app: *appname

# Cluster RBAC
rbac:
  # *appName- will be prepended to these keys in a template.
  clusterRoleNameSuffix: cluster-viewer
  clusterRoleBindingSuffix: clusterrolebinding

# K8s Service
service:
  type: LoadBalancer
  name: ssh
  protocol: TCP
  port: 22
  targetPort: 22
  # If loadBalancerIP is set, the service will be created with a static MetalLB IP addr
  # otherwise a VIP IP will be selected from the pool
  loadBalancerIP: 192.168.88.65
