#
# Apply with:
# gcloud beta container fleet config-management apply --membership=gdce-homelab \
# --config=config-sync-config.yaml --project=living-on-the-edge
#
applySpecVersion: 1
spec:
  upgrades: manual
  configSync:
    enabled: true
    sourceType: git
    sourceFormat: unstructured
    syncRepo: https://github.com/Ben-Chapman/Living-on-the-Edge-Root-Sync.git
    syncRev: main
    secretType: token
    # gcpServiceAccountEmail: EMAIL
    # metricsGcpServiceAccountEmail: METRICS_EMAIL
    policyDir: config-sync/root-sync
    preventDrift: false # b/345455587#comment11
