apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.dbName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.dbName }}
  replicas: {{ .Values.dbReplicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.dbName }}
    spec:
      containers:
      - name: {{ .Values.dbName }}
        image: {{ .Values.dbImage }}
        resources: {}
        ports:
        - containerPort: {{ .Values.dbSourcePort }}
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: db-data-volume
        env:
        {{- range $key, $val := .Values.dbEnv }}
        - name: {{ $key | upper }}
          value: {{ $val | quote }}
        {{- end }}
      volumes:
      - name: db-data-volume
        persistentVolumeClaim:
          claimName: db-data-claim

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dbName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.dbName }}
spec:
  ports:
  - port: {{ .Values.dbVipPort }}
    targetPort: {{ .Values.dbSourcePort }}
    protocol: TCP
  selector:
    app: {{ .Values.dbName }}
