apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-claim
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteOncePod
  resources:
    requests:
      storage: 1Gi
  storageClassName: robin-repl-2
