# Copyright 2024 Google. This software is provided as-is, without warranty or
# representation for any use or purpose. Your use of it is subject to your agreement
# with Google.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: '{{ .Values.name }}-{{ .Values.rbac.clusterRoleNameSuffix }}'
  labels:
    # Add these permissions to the "view" default role.
    rbac.authorization.k8s.io/aggregate-to-view: 'true'
rules:
  - apiGroups:
      - ''
    resources:
      - '*'
    verbs:
      - 'get'
      - 'list'
      - 'watch'

  - apiGroups:
      - ''
    resources:
      - pods/portforward
      - pods/exec
      - pods
    verbs:
      - 'create'
      - 'update'
      - 'attach'

  - apiGroups:
      - 'subresources.kubevirt.io'
    resources:
      - virtualmachineinstances/console
      - virtualmachineinstances/ssh
      - virtualmachineinstances/vnc
      - virtualmachineinstances/portforward
      - virtualmachines/portforward
      - virtualmachines/start
      - virtualmachines/stop
      - virtualmachines/soft-reboot
    verbs:
      - 'get'
      - 'update'
