apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachineDisk
metadata:
  name: windowsxp-boot
  namespace: vms
spec:
  source:
    gcs:
      url: gs://living-on-the-edge-vm-images/winxp.qcow2
      secretRef: vm-image-importer
  size: 12Gi
  storageClassName: robin-vm-repl-2-block-immediate
